type: custom:apexcharts-card
graph_span: 1month
span:
  start: month
header:
  title: Monthly Balance (kWh)
  show: true
apex_config:
  chart:
    stacked: true
    stackType: normal
    animations:
      enabled: false
  xaxis:
    type: datetime
    tickAmount: 31
    labels:
      format: dd
series:
  - entity: sensor.ec_imported_residual_energy_day
    name: Imported
    color: rgba(0, 128, 255, 1)
    type: column
    stack_group: energy
    group_by:
      func: last
      duration: 1d
      fill: zero
    show:
      in_legend: true
      legend_value: false
      in_chart: true
  - entity: sensor.ec_produced_energy_day
    name: Production
    color: rgba(233, 188, 5, 1)
    type: column
    stack_group: energy
    group_by:
      func: last
      duration: 1d
      fill: zero
    show:
      in_legend: true
      legend_value: false
      in_chart: true
  - entity: sensor.ec_exported_residual_energy_day
    name: Returned
    color: rgba(127, 17, 224, 1)
    type: column
    stack_group: energy
    transform: |
      const v = Number(x);
      if (!isFinite(v)) return null;
      return -Math.abs(v);
    group_by:
      func: last
      duration: 1d
      fill: zero
    show:
      in_legend: true
      legend_value: false
      in_chart: true
  - entity: sensor.ec_exported_battery_energy_day
    name: Battery
    color: rgba(52, 168, 83, 1)
    type: column
    stack_group: energy
    transform: |
      const v = Number(x);
      if (!isFinite(v)) return null;
      return -Math.abs(v);
    group_by:
      func: last
      duration: 1d
      fill: zero
    show:
      in_legend: true
      legend_value: false
      in_chart: true
  - entity: sensor.ec_self_stored_energy_day
    name: Battery (Production)
    color: rgba(52, 168, 83, 1)
    type: column
    stack_group: energy
    group_by:
      func: last
      duration: 1d
      fill: zero
    show:
      in_legend: false
  - entity: sensor.ec_imported_battery_energy_day
    name: Battery (Imported)
    color: rgba(52, 168, 83, 1)
    type: column
    stack_group: energy
    group_by:
      func: last
      duration: 1d
      fill: zero
    show:
      in_legend: false
